sudo: required
servivces:
  - docker

before_install:
  - docker build -t pranith05/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pranith05/react-test npm test -- --coverage

after_success:
  - docker build -t pranith05/multi-client ./client
  - docker build -t pranith05/multi-nginx ./nginx
  - docker build -t pranith05/multi-server ./server
  - docker build -t pranith05/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push pranith05/multi-client
  - docker push pranith05/multi-nginx
  - docker push pranith05/multi-server
  - docker push pranith05/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: mutli-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-753035745486
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
